name: Pull latest build from Parent repo

# on: 
#     repository_dispatch:
#         types: [my-event]
on:
  workflow_dispatch:

jobs:
  pull_update:
    name: 'Pull latest Build'
    runs-on: ubuntu-latest
    steps:

    - name: 'Checking out repo code'
      uses: actions/checkout@v2

    - name: 'Get_dist'
      shell: bash
      run: |
        curl -L -O https://github.com/Azure/Synapse-workspace-deployment/archive/refs/tags/V1.7.0.tar.gz
        tar -xf V1.7.0.tar.gz
        cp -rf ./Synapse-workspace-deployment-1.7.0/dist/index.js ./dist/index.js
        sed -i 's/throw new Error("Checkstatus => status: " + resStatus + "; status message: " + msg);/logger_1.SystemLogger.warn("Checkstatus => status: " + resStatus + "; status message: " + msg);/g' ./dist/index.js
        sed -i 's/throw new Error("Artifact deployment validation failed : " + body);/logger_1.SystemLogger.warn("Artifact deployment validation failed : " + body);/g' ./dist/index.js
    
    - name: Modifiy the specific files using action
      run: |
        git config user.name "HarshaMaddipudi"
        git config user.email "harsha.maddipudi@kroger.com"
        git add ./dist/index.js
        git commit -m "updated dist"
        git push
    
    - name: 'create_release'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        files: '*'
